from form_schema import blank_form_data


def initial_cleanup_records() -> list[dict]:
    first_record = blank_form_data()
    first_record.update(
        {
            "intern_name": "Sample Intern One",
            "computer_name": "ICT-PC-001",
            "recorded_computer_name": "ICT-PC-001",
            "office_department": "ICT Department",
            "practical_date": "2026-07-27",
            "supervisor": "jonyango",
            "windows_version": "Windows 11 Pro",
            "system_manufacturer": "Dell Inc.",
            "system_model": "OptiPlex",
            "installed_physical_ram": "8 GB",
            "processor": "Intel Core i5",
            "system_type": "64-bit",
            "total_disk_size_gb": "256",
            "free_space_before_gb": "118",
            "used_space_before_gb": "138",
            "free_space_after_gb": "143",
            "space_recovered_gb": "25",
            "computer_info_recorded": True,
            "available_disk_checked": True,
            "restore_point_created": True,
            "user_temp_deleted": True,
            "windows_temp_deleted": True,
            "recycle_bin_emptied": True,
            "dns_cache_command_executed": True,
            "store_cache_completed": True,
            "disk_cleanup_completed": True,
            "update_cache_cleared": True,
            "dism_operation_success": True,
            "sfc_no_violations": True,
            "windows_update_opened": True,
            "automatic_virtual_memory_enabled": True,
            "computer_restarted_successfully": True,
            "post_cleanup_disk_checked": True,
            "computer_starts_normally": True,
            "keyboard_works": True,
            "mouse_works": True,
            "internet_connection_works": True,
            "office_apps_open": True,
            "antivirus_active": True,
            "windows_firewall_active": True,
            "no_unexpected_errors": True,
            "activities_completed": "Completed Windows cleanup, cache clearing, repair checks, update check, virtual memory confirmation, and restart validation.",
            "disk_space_recovered_summary": "25 GB recovered.",
            "virtual_memory_learning": "Confirmed automatic page-file management keeps virtual memory sized by Windows.",
            "most_useful_command": "Get-PSDrive -Name C",
            "unresolved_problems": "None reported.",
            "marks_total": "92",
        }
    )

    second_record = blank_form_data()
    second_record.update(
        {
            "intern_name": "Sample Intern Two",
            "computer_name": "ICT-PC-002",
            "recorded_computer_name": "ICT-PC-002",
            "office_department": "Finance Office",
            "practical_date": "2026-07-27",
            "supervisor": "jonyango",
            "windows_version": "Windows 10 Pro",
            "system_manufacturer": "HP",
            "system_model": "ProDesk",
            "installed_physical_ram": "4 GB",
            "processor": "Intel Core i3",
            "system_type": "64-bit",
            "total_disk_size_gb": "500",
            "free_space_before_gb": "64",
            "used_space_before_gb": "436",
            "free_space_after_gb": "91",
            "space_recovered_gb": "27",
            "computer_info_recorded": True,
            "available_disk_checked": True,
            "restore_point_created": True,
            "user_temp_deleted": True,
            "windows_temp_deleted": True,
            "recycle_bin_emptied": True,
            "dns_cache_command_executed": True,
            "store_cache_completed": True,
            "disk_cleanup_completed": True,
            "update_cache_cleared": True,
            "dism_operation_success": True,
            "sfc_corrupt_repaired": True,
            "windows_update_opened": True,
            "restart_requirement_recorded": True,
            "automatic_virtual_memory_enabled": True,
            "computer_restarted_successfully": True,
            "post_cleanup_disk_checked": True,
            "computer_starts_normally": True,
            "keyboard_works": True,
            "mouse_works": True,
            "internet_connection_works": True,
            "office_apps_open": True,
            "printer_connection_works": True,
            "shared_folders_work": True,
            "antivirus_active": True,
            "windows_firewall_active": True,
            "no_unexpected_errors": True,
            "updates_installed": "Security update installed; restart completed.",
            "activities_completed": "Completed temporary-file cleanup, Windows Update cache cleanup, system repair checks, and post-cleanup testing.",
            "disk_space_recovered_summary": "27 GB recovered.",
            "virtual_memory_learning": "Automatic virtual memory should remain enabled unless an ICT supervisor approves a manual value.",
            "most_useful_command": "DISM.exe /Online /Cleanup-Image /RestoreHealth",
            "unresolved_problems": "None reported.",
            "marks_total": "90",
        }
    )

    return [first_record, second_record]
