"""initial schema

Revision ID: 91500de29217
Revises: 
Create Date: 2026-07-27 10:02:06.744696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91500de29217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_by_username', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleanup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleanup_records_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('cleanup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleanup_records_submitted_at'))

    op.drop_table('cleanup_records')
    # ### end Alembic commands ###
